### ISSUE TITLE
Demo: cashbomb.html demo always rejects payment on browsers that don't support IOv2

### ISSUE THREAD

**Issue by ChumpChief** [szager-chromium/IntersectionObserver#5]
I think the intent is to show something bad happening, but with IOv2 functionality the bad behavior is blocked - but clicking the initial screen just goes straight to payment rejection due to this condition:

https://github.com/szager-chromium/IntersectionObserver/blob/master/demo/cashbomb/cashbomb.html#L109

**Comment by szager-chromium** [comment]
I added feature detection to the demo code, should work as expected now (i.e., payments aren't rejected when IOv2 is not enabled).
